apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: us-central1-docker.pkg.dev/smiling-rhythm-339614/sampleapp-repo/sampleapp-gke:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
